"""Markdown report templates for NorthStar reporting engine."""

SESSION_REPORT_TEMPLATE = """\
# Session Report

**Session ID:** {session_id}
**Date:** {date}
**Duration:** {duration_minutes:.0f} minutes

---

## Summary

- Tasks started: {tasks_started_count}
- Tasks completed: {tasks_completed_count}
- Drift alerts: {drift_alerts_count}
- PDS (start): {pds_start:.0f}
- PDS (end): {pds_end:.0f}
- PDS change: {pds_change:+.0f}

## Tasks Started

{tasks_started_section}

## Tasks Completed

{tasks_completed_section}

## Decisions Made

{decisions_section}

## Drift Alerts

{drift_alerts_section}

## LLM Insights

{llm_insights}

---

*Generated by NorthStar Priority Debt Engine*
"""

WEEKLY_REPORT_TEMPLATE = """\
# Weekly Report

**Period:** {start_date} to {end_date}
**Sessions:** {session_count}
**Total Time:** {total_minutes:.0f} minutes

---

## Priority Debt Score Trend

{pds_trend}

## Top Accomplishments

{accomplishments_section}

## Debt Contributors

{debt_contributors_section}

## Session Summaries

{sessions_section}

## Recommendations

{recommendations_section}

## LLM Insights

{llm_insights}

---

*Generated by NorthStar Priority Debt Engine*
"""

RETROSPECTIVE_TEMPLATE = """\
# Retrospective

**Period:** {start_date} to {end_date}

---

## Predicted vs Actual

{predicted_vs_actual_section}

## Leverage Accuracy

- Average predicted leverage: {avg_predicted_leverage:.0f}
- Average actual outcome: {avg_actual_outcome:.0f}
- Accuracy ratio: {accuracy_ratio:.2f}

## What Went Well

{went_well_section}

## What Could Improve

{could_improve_section}

## Key Insights

{key_insights_section}

## LLM Analysis

{llm_analysis}

---

*Generated by NorthStar Priority Debt Engine*
"""
